name: Release

on:
  push:
    branches:
      - buffer-logins

jobs:

  container-main:
    uses: metal-toolbox/container-push/.github/workflows/container-push.yml@main
    with:
      name: audito-maldito
      tag: ${{ github.ref_name }}
      registry_org: ${{ github.repository }}
      dockerfile_path: Dockerfile
      platforms: linux/amd64,linux/arm64
